#!/bin/sh

# A wrapper script for GiniLinux-fs

KERNEL=linux-2.6.26.1

$KERNEL $@
# NOTE: first parameter MUST be of the form umid=
UMID=`echo $1 | sed -e 's/umid=\(.*\)/\1/g'`
if [ -e $GINI_HOME/tmp/$UMID ]; then
	rm $GINI_HOME/tmp/$UMID
    x=$4    
    x=${x#*,}
    x=${x%,*}
    x=${x%,*}
    x="$(echo ${x} | tr '[:lower:]' '[:upper:]')"
    x=$GINI_HOME/tmp/UML_bak/$x.sh
    cp $x $GINI_HOME/tmp
	glinux $@
fi
